[build]
  base = "."

  publish = "dist/"

  # Default build command.
  command = "npm run build"

# Disable NGSW

[[redirects]]
  from = "/ngsw.json"
  to = "/notfound"
  force = true
  status = 404

# SPA Fallbacks

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
